base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('register/', views.userregister, name='userregister'),
    path('login/', views.userlogin, name='userlogin'),
    path('logout/', views.userlogout, name='userlogout'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.getBlogs, name='getblogs'),
    path('blog/<int:pk>', views.getBlog, name='getblog'),
    path('create_blog/', views.createBlog, name='createblog'),
    path('edit_blog/<int:pk>', views.editBlog, name='editblog'),
    path('delete_blog/<int:pk>', views.deleteBlog, name='deleteblog'),
    path('delete_comment/<int:pk>', views.deleteComment, name='deletecomment'),
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    #Account
    path('', include('account.urls', namespace='account')),

    # Base
    path('', include('base.urls', namespace='base')),

    # Blog
    path('', include('blog.urls', namespace='blog')),
    
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Blog(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    datecreated = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title + ' by: ' + str(self.user)

class Comment (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    datetime = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.user.username + ' | blog post: ' + str(self.blog.id)

blog/forms.py
from django import forms
from .models import Blog, Comment


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'text', 'user')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'}),
            'user': forms.TextInput(attrs={'class': 'form-control', 'value': '', 'id': 'user', 'type': 'hidden'})
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment', 'blog', 'user')

        widgets = {
            'comment': forms.Textarea(attrs={'class': 'form-control', 'required': 'true'}),
            'user': forms.TextInput(attrs={'class': 'form-control', 'value': '', 'id': 'comment_user_id', 'type': 'hidden'}),
            'blog': forms.TextInput(attrs={'class': 'form-control', 'value': '', 'id': 'comment_blog_id', 'type': 'hidden'})
        }

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Blog, Comment
from .forms import BlogForm, CommentForm

# Create your views here.


def getBlogs(request):
    template = 'blog/blogs.html'
    blogs = Blog.objects.all()
    context = {
        'blogs': blogs
    }
    return render(request, template, context)


def getBlog(request, pk):
    template = 'blog/blog.html'
    blog = Blog.objects.get(pk=pk)
    comments = Comment.objects.filter(blog_id=pk)
    comment_form = CommentForm(request.POST or None, prefix='banned')

    if comment_form.is_valid():
        comment_form.save()
        return redirect('blog:getblog', pk=pk)

    context = {
        'blog': blog,
        'comment_form': comment_form,
        'comments': comments
    }
    return render(request, template, context)


def createBlog(request):
    template = 'blog/addblog.html'
    form = BlogForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('blog:getblogs')
    
    if (request.user.is_authenticated):
        context = {
            'form': form
        }

        return render(request, template, context)
    else:
        return redirect('blog:getblogs')


def editBlog(request, pk):
    template = 'blog/editblog.html'
    blog = get_object_or_404(Blog, pk=pk)
    form = BlogForm(request.POST or None, instance=blog)

    
    if form.is_valid():
        form.save()
        return redirect('blog:getblog', pk=pk)

    if (blog.user == request.user):
        context = {
            'form': form
        }

        return render(request, template, context)
    else:
        return redirect('blog:getblog', pk=pk)


def deleteBlog(request, pk):
    template = 'blog/deleteblog.html',
    blog = get_object_or_404(Blog, pk=pk)

    if blog.user == request.user:
        if request.method == 'POST':
            blog.delete()
            return redirect('blog:getblogs')
    else:
        return redirect('blog:getblog', pk=pk)

    context = {
        'blog': blog
    }

    return render(request, template, context)


def deleteComment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)

    if (comment.user == request.user):
        comment.delete()
        return HttpResponseRedirect(reverse('blog:getblog', args=(comment.blog_id,)))
    else:
        return HttpResponseRedirect(reverse('blog:getblog', args=(comment.blog_id,)))

blog/templates/blog/addblog.html
{% extends 'base/base.html' %} {% block content %}
<section class="section-box">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Add new blog</h1>
        <form method="POST" action="">
          {% csrf_token %} 
          {{ form.as_p }}
          <button class="btn btn-primary"><i class="fas fa-save"></i> Save Post</button>
        </form>
      </div>
    </div>
  </div>
</section>

<script>
  let name = "{{ user.id }}";
  document.querySelector("#user").value = name;
</script>

{% endblock %}

blog/templates/blog/blog.html
{% extends 'base/base.html' %} {% block content %}

<section class="section-box">
  <div class="container">
    <div class="row">
        <div class="col-md-12 text-right">
           {% if user.is_authenticated and user.id == blog.user.id %}
                <a class="btn btn-custom-success" href="{% url 'blog:editblog' blog.pk %}"><i class="fas fa-pencil-alt"></i> Edit</a>
                <a class="btn btn-custom-danger" href="{% url 'blog:deleteblog' blog.pk %}"><i class="fas fa-trash-alt"></i> Delete</a>
           {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="blog-post">
                <h1>
                    {{ blog.title }}
                    <span class="blog-post_date">{{ blog.datecreated }}</span>
                </h1>
                <p>
                    {{ blog.text|linebreaks }}
                </p>
            </div>
        </div>
    </div>
  </div>
</div>

<section class="section-box">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <form method="POST">
            <span>Comment as: {{ user.username }}</span>
            {% csrf_token %}
            <div class="form-group">
                {{ comment_form.comment }}
            </div>
            <div class="form-group">
                {{ comment_form.blog }}
            </div>
            <div class="form-group">
                {{ comment_form.user }}
            </div>
              <button class="btn btn-primary mt-3"{% if not user.is_authenticated %} disabled {% endif %}>Add Comment</button>
          </form>
          
        </div>
      </div>
    </div>
</section>

<section class="section-box">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
            <h2 class="heading-secondary">
                Comments:
            </h2>
            {% for comment in comments %}
                <div class="comment-box">
                    <h2 class="heading-secondary">
                        {% if comment.user.first_name or comment.user.last_name %}
                            {{ comment.user.first_name }} {{ comment.user.last_name }}
                        {% else %}
                            {{ comment.user.username }}
                        {% endif %}
                        <span class="blog-post_date">{{ comment.datetime }}</span>
                    </h2>
                    <p>
                        {{ comment.comment }}
                    </p>
                    {% if comment.user_id == user.id %}
                    <a class="btn btn-custom-danger p-0 btn-custom-size-sm" href="{% url 'blog:deletecomment' comment.id %}">
                        <i class="fas fa-trash-alt"></i> Delete
                    </a>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
      </div>
    </div>
</section>


<script>
    let user = "{{ user.id }}",
        blog = "{{ blog.id }}";

    document.querySelector('#comment_user_id').value = user;
    document.querySelector('#comment_blog_id').value = blog;

</script>

{% endblock %}

blog/templates/blog/blogs.html
{% extends 'base/base.html' %} {% block content %}
{% if user.is_authenticated %}
<section class="section-box">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-right">
          <a class="btn btn-custom-primary btn-blogs_add" href="{% url 'blog:createblog' %}">Add new blog <i class="fas fa-plus"></i></a>
      </div>
    </div>
  </div>
</section>
{% endif %}

<section class="section-box">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        {% for blog in blogs %}
        <div class="blog-posts">
          <div class="col-md-3 py-2">
            {{ blog.datecreated }}
          </div>
          <div class="col-md-9">
            <div class="blog_post">
              <h1 class="heading-primary">
                <a href="{% url 'blog:getblog' blog.pk %}">
                  {{ blog.title }}
                </a>
              </h1>
              <p class="blog_post-author">Author: {{ blog.user }}</p>
              <p class="blog_post-excerpt">{{ blog.text|truncatewords:10 }}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

blog/templates/blog/deleteblog.html
{% extends 'base/base.html' %} {% block content %}

<section class="section-box">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="form-container text-center">
          <form method='POST'>
            {% csrf_token %}
            <p class="blog-prompt">
                Are you sure you want to delete post?
            </p> 
            <input type="submit" class="btn btn-custom-danger" value="Yes">
            <a href="{% url 'blog:getblog' blog.pk %}" class="btn btn-custom-primary">No</a>
        </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

blog/templates/blog/editblog.html
{% extends 'base/base.html' %} {% block content %}
<section class="section-box">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Edit blog</h1>
        <form method="POST">
          {% csrf_token %} 
          {{ form.as_p }}
          <button class="btn btn-primary"><i class="fas fa-save"></i> Update Post</button>
        </form>
      </div>
    </div>
  </div>
</section>

<script>
  let name = "{{ user.id }}";
  document.querySelector("#user").value = name;
</script>

{% endblock %}