account/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView

app_name = 'account'

urlpatterns = [
    path('user_profile/', views.getUser, name='getuser'),
    path('change_password/', PasswordChangeView.as_view(success_url=reverse_lazy('account:change_password_complete'),
                                                        template_name='account/changepassword.html'), name='change_password'),
    path('change_password/complete/', PasswordChangeDoneView.as_view(template_name='account/changepassword_complete.html'),
         name='change_password_complete'),
]

base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('register/', views.userregister, name='userregister'),
    path('login/', views.userlogin, name='userlogin'),
    path('logout/', views.userlogout, name='userlogout'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.getBlogs, name='getblogs'),
    path('blog/<int:pk>', views.getBlog, name='getblog'),
    path('create_blog/', views.createBlog, name='createblog'),
    path('edit_blog/<int:pk>', views.editBlog, name='editblog'),
    path('delete_blog/<int:pk>', views.deleteBlog, name='deleteblog'),
    path('delete_comment/<int:pk>', views.deleteComment, name='deletecomment'),
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    #Account
    path('', include('account.urls', namespace='account')),

    # Base
    path('', include('base.urls', namespace='base')),

    # Blog
    path('', include('blog.urls', namespace='blog')),
    
]

base/models.py
from django.db import models

# Create your models here.

base/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

# Models
from django.contrib.auth.models import User

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
        ]

base/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from .forms import UserRegistrationForm

# Create your views here.


def userregister(request):
    form = UserRegistrationForm()

    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('base:userlogin')

    context = {
        'form': form
    }
    return render(request, 'base/userregister.html', context)


def userlogin(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('blog:getblogs')
        else:
            messages.info(request, 'Username or Password is Incorrect')

    context = {}
    return render(request, 'base/userlogin.html', context)


def userlogout(request):

    logout(request)
    return redirect('base:userlogin')

base/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Bootstrap -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css"
      integrity="sha512-P5MgMn1jBN01asBgU0z60Qk4QxiXo86+wlFahKrsQf37c9cro517WzVSPPV1tDKzhku2iJ2FVgL67wG03SGnNA=="
      crossorigin="anonymous"
    />

    <!-- Bootswatch  -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Lora:wght@400;600&display=swap"
      rel="stylesheet"
    />

    <!-- Font-Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
      integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
      crossorigin="anonymous"
    />

    <!-- Custom Style -->
    <link
      rel="stylesheet"
      href="{% static 'css/styles.css' %}"
      type="text/css"
    />

    <title>Django Blog</title>
  </head>
  <body>
    <!-- Header -->
    {% include 'base/navbar.html'%}
    <!-- Main -->
    {% block content %}{% endblock %}
    <!-- Footer -->
    <!-- <footer>Footer</footer> -->
    <!-- Scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"
      integrity="sha512-XKa9Hemdy1Ui3KSGgJdgMyYlUg1gM+QhL6cnlyTe2qzMCYm4nAZ1PsVerQzTTXzonUR+dmswHqgJPuwCq1MaAg=="
      crossorigin="anonymous"
    ></script>
  </body>
</html>

base/templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <div class="row w-100">
      <div class="col-md-3">
        <a class="navbar-brand" href="{% url 'blog:getblogs' %}">Django Blog</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarColor01"
          aria-controls="navbarColor01"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="col-md-9">
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                data-toggle="dropdown"
                href="#"
                role="button"
                aria-haspopup="true"
                aria-expanded="false"
                >{{ user.username|title }}</a
              >
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'account:getuser' %}"
                  >User Profile</a
                >
                <a
                  class="dropdown-item"
                  href="{% url 'account:change_password' %}"
                  >Change Password</a
                >
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'base:userlogout' %}"
                >Sign out</a
              >
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'base:userlogin' %}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'base:userregister' %}"
                >Register</a
              >
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>

base/templates/base/userlogin.html
{% extends 'base/base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="form-container">
        <div class="form-div">
          <h1>Sign In</h1>
          <form method="POST" action="">
            {% csrf_token %}
            <div class="form-group">
              <label for="username">Username</label>
              <input
                type="text"
                class="form-control"
                id="username"
                name="username"
                placeholder="Enter Username"
              />
            </div>
            <div class="form-group">
              <label for="password">Password</label>
              <input
                type="password"
                class="form-control"
                id="password"
                name="password"
                placeholder="Password"
              />
            </div>
            <input type="submit" class="btn btn-primary" value="Log in" />
          </form>
          {% for message in messages %}
          <p>{{message}}</p>
          {% endfor %}
          <div class="mt-3">
            Don't have an account?
            <a href="{% url 'base:userregister' %}">Register</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

base/templates/base/userregister.html
{% extends 'base/base.html' %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="form-container">
        <div class="form-div">
          <h1>Sign Up</h1>
          <form method="POST" action="">
            {% csrf_token %}
            <div class="form-group">
              <label for="first_name">First Name</label>
              <input
                type="text"
                class="form-control"
                id="first_name"
                name="first_name"
                placeholder="First Name"
              />
            </div>
            <div class="form-group">
              <label for="last_name">Last Name</label>
              <input
                type="text"
                class="form-control"
                id="last_name"
                name="last_name"
                placeholder="Last Name"
              />
            </div>
            <div class="form-group">
              <label for="username">Username</label>
              <input
                type="text"
                class="form-control"
                id="username"
                name="username"
                placeholder="Enter desired username"
              />
            </div>
            <div class="form-group">
              <label for="email">Email Address</label>
              <input
                type="email"
                class="form-control"
                id="email"
                name="email"
                placeholder="Email Address"
              />
            </div>
            <div class="form-group">
              <label for="password1">Password</label>
              <input
                type="password"
                class="form-control"
                id="password1"
                name="password1"
                placeholder="Password"
              />
            </div>
            <div class="form-group">
              <label for="password2">Confirm Password</label>
              <input
                type="password"
                class="form-control"
                id="password2"
                name="password2"
                placeholder="Confirm Password"
              />
            </div>
            <input class="btn btn-primary" type="submit" value="Create User" />
          </form>
          {{form.errors}}
        </div>
        <div class="mt-3">
          Already have an account?
          <a href="{% url 'base:userlogin' %}">Login</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}